stages:
  - build
  - release

before_script:
  - if test "x$(uname -s)" == "xDarwin"; then eval $(docker-machine env default); fi
  - docker login -u gitlab-ci-token -p $CI_BUILD_TOKEN $CI_REGISTRY

build:image:php5.6-apache:
  stage: build
  variables:
    BUILD_IMAGE: $CI_REGISTRY_IMAGE:php5.6-apache
    LEGACY_IMAGE: $CI_REGISTRY_IMAGE:master
  only:
    - master
  tags:
    - shell-executor
    - docker
  script:
    - docker build --pull -t $BUILD_IMAGE -f php5.6-apache/Dockerfile .
    - docker push $BUILD_IMAGE
    - docker tag $BUILD_IMAGE $LEGACY_IMAGE
    - docker push $LEGACY_IMAGE

build:image:php5.6-apache-alpine:
  stage: build
  variables:
    BUILD_IMAGE: $CI_REGISTRY_IMAGE:php5.6-apache-alpine
  only:
    - master
  tags:
    - shell-executor
    - docker
  script:
    - docker build --pull -t $BUILD_IMAGE -f php5.6-apache-alpine/Dockerfile .
    - docker push $BUILD_IMAGE

release:image:
  stage: release
  variables:
    BUILD_IMAGE: $CI_REGISTRY_IMAGE:php5.6-apache
    RELEASE_IMAGE: $CI_REGISTRY_IMAGE:latest
  only: 
    - master
  tags:
    - shell-executor
    - docker
  script:
    - docker pull $BUILD_IMAGE
    - docker tag $BUILD_IMAGE $RELEASE_IMAGE
    - docker push $RELEASE_IMAGE

